apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: sentry-cron
    app: sentry-cron
  name: sentry-cron
spec:
  replicas: 1
  selector:
    name: sentry-cron
    app: sentry-cron
  template:
    metadata:
      labels:
        name: sentry-cron
        app: sentry-cron
    spec:
      containers:
      - name: sentry-cron
        env:
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret_key
              name: sentry-base
        - name: SENTRY_POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              key: postgres_host
              name: sentry-base
        - name: SENTRY_POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              key: postgres_port
              name: sentry-base
        - name: SENTRY_DB_NAME
          valueFrom:
            secretKeyRef:
              key: postgres_db_name
              name: sentry-base
        - name: SENTRY_DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-credentials
        - name: SENTRY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-credentials
        - name: SENTRY_REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: redis_host
              name: sentry-base
        - name: SENTRY_REDIS_PORT
          valueFrom:
            secretKeyRef:
              key: redis_port
              name: sentry-base
        - name: SENTRY_SERVER_EMAIL
          valueFrom:
            secretKeyRef:
              key: server_email
              name: sentry-base
        - name: SENTRY_EMAIL_HOST
          valueFrom:
            secretKeyRef:
              key: email_host
              name: sentry-base
        - name: SENTRY_EMAIL_PORT
          valueFrom:
            secretKeyRef:
              key: email_port
              name: sentry-base
        - name: SENTRY_EMAIL_USER
          valueFrom:
            secretKeyRef:
              key: email_user
              name: sentry-base
        - name: SENTRY_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: email_password
              name: sentry-base
        - name: SENTRY_EMAIL_USE_TLS
          valueFrom:
            secretKeyRef:
              key: email_use_tls
              name: sentry-base
        - name: SENTRY_SINGLE_ORGANIZATION
          valueFrom:
            secretKeyRef:
              key: single_organization
              name: sentry-base
        image: sentry/sentry:v1
        imagePullPolicy: IfNotPresent
        args: ['run', 'cron']
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
