apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentry-web
  name: sentry-web
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 9000
  selector:
    app: sentry-web
  sessionAffinity: None
  type: ClusterIP
